#!/bin/sh
# Bundles the calculator modules from the Calculum website into
# Calculum/Resources/engine.js, then checks every calculator in JavaScriptCore.
# The website checkout defaults to ~/www/calculum.dev. Override it with
# CALCULUM_WEB=/path/to/calculum.dev scripts/build-engine.sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
WEB=${CALCULUM_WEB:-"$HOME/www/calculum.dev"}
OUT="$ROOT/Calculum/Resources/engine.js"

if [ ! -d "$WEB/src/data" ]; then
  echo "Can't find the website's calculator modules in $WEB/src/data" >&2
  exit 1
fi

COMMIT=$(git -C "$WEB" rev-parse --short HEAD 2>/dev/null || echo unknown)

cd "$ROOT"
"$WEB/node_modules/.bin/esbuild" engine/entry.js \
  --bundle --format=iife --platform=neutral --target=es2020 \
  --alias:@site="$WEB/src" \
  --banner:js="// Calculum calculator engine, generated by scripts/build-engine.sh from calculum.dev@$COMMIT. Don't edit by hand." \
  --log-level=warning \
  --outfile="$OUT"

# esbuild labels each module with its path relative to this repo. Keep only
# the part inside the website, so the bundle doesn't depend on where it lives.
sed -i '' -E 's#^(  // )[^ ]*/src/#\1calculum.dev/src/#' "$OUT"

swift scripts/check-engine.swift "$OUT"
